name: odgs-rtr
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # === PyTorch (CUDA 11.8) ===
  - pytorch=2.1.2=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8
  - torchvision=0.16.2=py310_cu118
  - torchaudio=2.1.2=py310_cu118
  # === Python packages (conda) ===
  - numpy=1.26.4
  - matplotlib=3.5.2
  - pillow
  - tensorboard=2.10.0
  - tqdm
  - opencv
  - scipy
  - scikit-image
  # === Pip packages ===
  - pip:
      - plyfile
      - dearpygui
      - imageio
      - imageio-ffmpeg
      - OpenEXR
      - PyEXR
      - open3d
      - trimesh
  